apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: {{ .Values.elasticsearch.image }}
          env:
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: {{ .Values.elasticsearch.port }}
          resources:
            {{- toYaml .Values.elasticsearch.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: {{ .Values.elasticsearch.serviceType }}
  ports:
    - port: {{ .Values.elasticsearch.port }}
      targetPort: {{ .Values.elasticsearch.port }}
  selector:
    app: elasticsearch
